-- MySQL Script generated by MySQL Workbench
-- vie 16 oct 2020 10:34:27 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `apellido_cliente` VARCHAR(45) NOT NULL,
  `correo_cliente` VARCHAR(45) NOT NULL,
  `contrasena_cliente` VARCHAR(45) NOT NULL,
  `conf_contrasena` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `pais_cliente` VARCHAR(30) NOT NULL,
  `foto_cliente` VARCHAR(100) NOT NULL,
  `credito_cliente` INT NOT NULL,
  `tipo_usuario` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrito` (
  `id_carrito_compra` INT NOT NULL AUTO_INCREMENT,
  `cantidad_` INT NOT NULL,
  `precio_unitario` INT NOT NULL,
  `subtotal` INT NOT NULL,
  `CLIENTE_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_carrito_compra`),
  INDEX `fk_Carrito_CLIENTE1_idx` (`CLIENTE_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Carrito_CLIENTE1`
    FOREIGN KEY (`CLIENTE_id_cliente`)
    REFERENCES `mydb`.`USUARIO` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMPRA` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `Carrito_id_carrito_compra` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_COMPRA_Carrito1_idx` (`Carrito_id_carrito_compra` ASC) VISIBLE,
  CONSTRAINT `fk_COMPRA_Carrito1`
    FOREIGN KEY (`Carrito_id_carrito_compra`)
    REFERENCES `mydb`.`Carrito` (`id_carrito_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENTA` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `CLIENTE_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_VENTA_CLIENTE1_idx` (`CLIENTE_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_VENTA_CLIENTE1`
    FOREIGN KEY (`CLIENTE_id_cliente`)
    REFERENCES `mydb`.`USUARIO` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `detalle_producto` VARCHAR(150) NOT NULL,
  `parabras_clave` VARCHAR(200) NOT NULL,
  `precio_producto` INT NOT NULL,
  `me_gusta` INT NOT NULL,
  `no_me_gusta` INT NOT NULL,
  `CATEGORIA_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_PRODUCTO_CATEGORIA1_idx` (`CATEGORIA_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_id_categoria`)
    REFERENCES `mydb`.`CATEGORIA` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_COMPRA` (
  `id_detalle_compra` INT NOT NULL AUTO_INCREMENT,
  `cantidad_compra` VARCHAR(45) NOT NULL,
  `COMPRA_id_compra` INT NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_detalle_compra`),
  INDEX `fk_DETALLE_COMPRA_COMPRA1_idx` (`COMPRA_id_compra` ASC) VISIBLE,
  INDEX `fk_DETALLE_COMPRA_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_COMPRA_COMPRA1`
    FOREIGN KEY (`COMPRA_id_compra`)
    REFERENCES `mydb`.`COMPRA` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_COMPRA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_VENTA` (
  `id_detalle_venta` INT NOT NULL AUTO_INCREMENT,
  `cantidad_venta` VARCHAR(45) NOT NULL,
  `VENTA_id_venta` INT NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_detalle_venta`),
  INDEX `fk_DETALLE_VENTA_VENTA1_idx` (`VENTA_id_venta` ASC) VISIBLE,
  INDEX `fk_DETALLE_VENTA_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_VENTA_VENTA1`
    FOREIGN KEY (`VENTA_id_venta`)
    REFERENCES `mydb`.`VENTA` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_VENTA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PUBLICACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PUBLICACION` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_publicacion` DATE NOT NULL,
  `cantidad_publicacion` INT NOT NULL,
  `CLIENTE_id_cliente` INT NOT NULL,
  `estado_publicacion` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `fk_PUBLICACION_CLIENTE_idx` (`CLIENTE_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_PUBLICACION_CLIENTE`
    FOREIGN KEY (`CLIENTE_id_cliente`)
    REFERENCES `mydb`.`USUARIO` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DENUNCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DENUNCIA` (
  `id_denuncia` INT NOT NULL AUTO_INCREMENT,
  `fecha_publicacion_denuncia` DATE NOT NULL,
  `descripcion_denuncia` VARCHAR(200) NOT NULL,
  `cantidad_denuncia` INT NOT NULL,
  `PUBLICACION_id_publicacion` INT NOT NULL,
  PRIMARY KEY (`id_denuncia`),
  INDEX `fk_DENUNCIA_PUBLICACION1_idx` (`PUBLICACION_id_publicacion` ASC) VISIBLE,
  CONSTRAINT `fk_DENUNCIA_PUBLICACION1`
    FOREIGN KEY (`PUBLICACION_id_publicacion`)
    REFERENCES `mydb`.`PUBLICACION` (`id_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BITACORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BITACORA` (
  `id_bitacora` INT NOT NULL AUTO_INCREMENT,
  `descripcion_bitacora` VARCHAR(50) NOT NULL,
  `fecha_accion_bitacora` DATE NOT NULL,
  `correo_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_bitacora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMENTARIO` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `fecha_comentario` DATE NOT NULL,
  `descripcion_comentario` VARCHAR(100) NOT NULL,
  `CLIENTE_id_cliente` INT NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_COMENTARIO_CLIENTE1_idx` (`CLIENTE_id_cliente` ASC) VISIBLE,
  INDEX `fk_COMENTARIO_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_COMENTARIO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_id_cliente`)
    REFERENCES `mydb`.`USUARIO` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

